# Complete CI/CD Pipeline for GKE Deployment
# This pipeline builds, tests, scans, and deploys both backend and frontend to GKE

substitutions:
  _PROJECT_ID: 'btoproject-486405-486604'
  _REGION: 'us-central1'
  _GKE_CLUSTER: 'chatbot-rag-gke'
  _CLUSTER_ZONE: 'us-central1-a'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/btoproject-486405-486604/chatbot-rag-images'
  _BACKEND_IMAGE: '${_ARTIFACT_REGISTRY}/backend'
  _FRONTEND_IMAGE: '${_ARTIFACT_REGISTRY}/frontend'

timeout: 3600s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

steps:
  # Backend: Build → Test → Scan → Push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args: ['build', '-t', '${_BACKEND_IMAGE}:$COMMIT_SHA', '-t', '${_BACKEND_IMAGE}:latest', '.']
    waitFor: ['-']

  - name: '${_BACKEND_IMAGE}:$COMMIT_SHA'
    id: 'test-backend'
    entrypoint: 'pytest'
    args: ['tests/', '--cov=app', '--cov-report=xml', '-v']
    env: ['ENVIRONMENT=test']
    waitFor: ['build-backend']

  - name: 'aquasec/trivy:latest'
    id: 'scan-backend'
    args: ['image', '--exit-code', '0', '--severity', 'HIGH,CRITICAL', '${_BACKEND_IMAGE}:$COMMIT_SHA']
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args: ['push', '--all-tags', '${_BACKEND_IMAGE}']
    waitFor: ['test-backend', 'scan-backend']

  # Frontend: Build → Scan → Push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args: ['build', '-t', '${_FRONTEND_IMAGE}:$COMMIT_SHA', '-t', '${_FRONTEND_IMAGE}:latest', '-f', 'frontend/Dockerfile', './frontend']
    waitFor: ['-']

  - name: 'aquasec/trivy:latest'
    id: 'scan-frontend'
    args: ['image', '--exit-code', '0', '--severity', 'HIGH,CRITICAL', '${_FRONTEND_IMAGE}:$COMMIT_SHA']
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', '--all-tags', '${_FRONTEND_IMAGE}']
    waitFor: ['scan-frontend']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    args: ['container', 'clusters', 'get-credentials', '${_GKE_CLUSTER}', '--zone=${_CLUSTER_ZONE}', '--project=${_PROJECT_ID}']
    waitFor: ['push-backend', 'push-frontend']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-backend'
    args: ['set', 'image', 'deployment/rag-backend', 'rag-backend=${_BACKEND_IMAGE}:$COMMIT_SHA', '-n', 'default']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor: ['get-credentials']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-frontend'
    args: ['set', 'image', 'deployment/rag-frontend', 'rag-frontend=${_FRONTEND_IMAGE}:$COMMIT_SHA', '-n', 'default']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor: ['get-credentials']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'rollout-status-backend'
    args: ['rollout', 'status', 'deployment/rag-backend', '-n', 'default', '--timeout=600s']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor: ['deploy-backend']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'rollout-status-frontend'
    args: ['rollout', 'status', 'deployment/rag-frontend', '-n', 'default', '--timeout=600s']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor: ['deploy-frontend']

images:
  - '${_BACKEND_IMAGE}:$COMMIT_SHA'
  - '${_BACKEND_IMAGE}:latest'
  - '${_FRONTEND_IMAGE}:$COMMIT_SHA'
  - '${_FRONTEND_IMAGE}:latest'

tags: ['gke-deployment', 'chatbot-rag', '$COMMIT_SHA']
