apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-backend-sa
  annotations:
    iam.gke.io/gcp-service-account: rag-service@botpproject.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-frontend-sa
  annotations:
    iam.gke.io/gcp-service-account: rag-service@botpproject.iam.gserviceaccount.com
